[package]
name = "wasm-game"
version = "0.1.0"
authors = ["xiaolatiao <1628652790@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
